server:
  port: 8081

spring:
  application:
    name: students-service
  datasource:
    url: jdbc:postgresql://postgres-students:5432/simplehrms_students
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: students-service
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30

springdoc:
  api-docs:
    enabled: true
    path: /students/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

openapi:
  service:
    title: ${spring.application.name}
    version: 1.0.0
    url: http://students-service:${server.port}